account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import CustomLoginView, RegisterPage

app_name = 'account'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout')
]

chat_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),

]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:username>_chat/', views.chat_page, name='chat-page')
]

account/models.py
from django.db import models

# Create your models here.

core/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(null=True, blank=True, max_length=60)
    content = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ('date',)

account/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.views.generic import FormView
from django.urls import reverse_lazy


class CustomLoginView(LoginView):
    template_name = 'account/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('core:index')


class RegisterPage(FormView):
    template_name = 'account/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('core:index')
        return super(RegisterPage, self).get(*args, **kwargs)

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from core.models import Message


@login_required
def index(request):
    users = User.objects.exclude(username=request.user.username)
    return render(request, "core/index.html", context={'users': users})


@login_required
def chat_page(request, username):
    user_obj = User.objects.get(username=username)
    users = User.objects.exclude(username=request.user.username)

    if request.user.id > user_obj.id:
        title = f'{request.user.id}-{user_obj.id}'
    else:
        title = f'{user_obj.id}-{request.user.id}'
    message_objs = Message.objects.filter(title=title)
    return render(request, 'core/chat_page.html', context={'user': user_obj, 'users': users, 'messages': message_objs})

core/templates/core/base.html
{% load static %}

<!doctype html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        body {
            font-family: 'Nunito', sans-serif;
        }
    </style>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>


</head>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>


<section style="background-color: #CDC4F9;">

<div class="d-flex justify-content-end">
    {% if request.user.is_authenticated %}
        <a href="{% url 'core:index' %}" class="btn" style="font-weight: bold">{{ request.user.username }}</a>
        <a href="{% url 'account:logout' %}" class="btn" style="font-weight: bold">Logout</a>
    {% else %}
        <a href="{% url 'account:login' %}" class="btn" style="font-weight: bold">Login</a>
    {% endif %}
</div>

  <div class="container py-5">

    <div class="row">
      <div class="col-md-12">

        <div class="card" id="chat3" style="border-radius: 15px;">
          <div class="card-body">


            {% block content %}
            {% endblock %}

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% block javascript %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

core/templates/core/chat_page.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="row">

      <div class="col-md-6 col-lg-5 col-xl-4 mb-4 mb-md-0">

        <table class="table">
          <tbody>
            {% for user in users %}
            <tr>
              <td><a href="{% url 'core:chat-page' username=user.username %}">{{user.username}}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>


      <div class="col-md-6 col-lg-7 col-xl-8">

       <div class="" style="position: relative; height: 400px; overflow-y: scroll;">
          <table class="table">
            <tbody id="chat-body">
              {% for message in messages %}
              {% if message.author == request.user %}
              <tr>
                <td>
                  <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded" style="display: inline-block;">
                    {{ message.content }}
                  </p>
                </td>
                <td>
                  <p><small class="p-1 shadow-sm">{{ message.date|time:'H:i' }}</small></p>
                </td>
              </tr>
              {% else %}
              <tr>
                <td>
                  <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded" style="display: inline-block;">
                    {{ message.content }}
                  </p>
                </td>
                <td>
                  <p><small class="p-1 shadow-sm">{{ message.date|time:'H:i' }}</small></p>
                </td>
              </tr>
              {% endif %}
              {% endfor %}
            </tbody>
          </table>
    </div>


        <div class="text-muted d-flex justify-content-start align-items-center pe-3 pt-3 mt-2">
          <div class="row message-box p-3">
            <div class="col-sm-2 mt-2">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
              </svg>
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2"
                fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              </svg>
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cash" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
              </svg>
            </div>
            <div class="col-sm-8">
              <input type="text" id="message_input" class="form-control form-control-lg"
                placeholder="Type message">
            </div>
            <div class="col-sm-2 mt-1">
              <div class="control">
                <button id="chat-message-submit" class="btn" style="background-color: #CDC4F9; color: #ffffff; font-weight: bold;">Submit</button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

{{user.id|json_script:"json-username"}}
{{request.user.username|json_script:"json-message-username"}}
{{message.date|json_script:"json-message-date"}}
{% endblock %}

{% block javascript %}
<script type="text/javascript">

const id = JSON.parse(document.getElementById('json-username').textContent);
const message_username = JSON.parse(document.getElementById('json-message-username').textContent);
const message_date = JSON.parse(document.getElementById('json-message-date').textContent);

const socket = new WebSocket(
    'ws://'
    + window.location.host
    + '/ws/'
    + id
    + '/'
);

socket.onopen = function(e){
    console.log("CONNECTION ESTABLISHED");
}

socket.onclose = function(e){
    console.log("CONNECTION LOST");
}

socket.onerror = function(e){
    console.log("ERROR OCCURED");
}

socket.onmessage = function(e){
    const data = JSON.parse(e.data);
    const message_date = data.timestamp
    if(data.username === message_username){
        document.querySelector('#chat-body').innerHTML += `<tr>
                                                                <td>
                                                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded" style="display: inline-block;">${data.message}</p>
                                                                 <td>
                                                                    <p><small class="p-1 shadow-sm">${message_date}</small></p>
                                                                </td>
                                                                </td>
                                                            </tr>`
    }else{
        document.querySelector('#chat-body').innerHTML += `<tr>
                                                                <td>
                                                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded" style="display: inline-block;">${data.message}</p>
                                                                <td>
                                                                    <p><small class="p-1 shadow-sm">${message_date}</small></p>
                                                                </td>
                                                                </td>
                                                            </tr>`
    }
}

document.querySelector('#chat-message-submit').onclick = function(e){
    const message_input = document.querySelector('#message_input');
    const message = message_input.value;

    socket.send(JSON.stringify({
        'message': message,
        'username': message_username,
    }));

    message_input.value = '';
}

</script>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

   <div class="col-md-6 col-lg-5 col-xl-4 mb-4 mb-md-0">

        <table class="table table-borderless">
          <tbody>
            {% for user in users %}
            <tr>
              <td><a href="{% url 'core:chat-page' username=user.username %}">{{user.username}}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

  </div>

{% endblock %}